### ISSUE TITLE
dir produces duplicate output

### ISSUE THREAD

**Issue by dodamih** [ZettaAI/zetta_utils#129]
When `dir(encoding_coarsener)` is called on an instance of EncodingCoarsener, the 'encoder' and the 'decoder' are duplicated.

Sample output: 
(Pdb) `dir(pl_module)
['CHECKPOINT_HYPER_PARAMS_KEY', 'CHECKPOINT_HYPER_PARAMS_NAME', 'CHECKPOINT_HYPER_PARAMS_TYPE', 'T_destination', '_DeviceDtypeModuleMixin__update_properties', '_LightningModule__check_allowed', 
'_LightningModule__check_not_nested', '_LightningModule__to_tensor', '__annotations__', '__attrs_attrs__', '__attrs_own_setattr__', '__attrs_pre_init__', '__call__', '__class__', '__delattr__', '__dict__', 
'__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_builder_spec', '__init_subclass__', 
'__jit_unused_properties__', '__le__', '__lt__', '__match_args__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__setstate__', '__sizeof__', '__slots__', 
'__str__', '__subclasshook__', '__weakref__', '_apply', '_apply_batch_transfer_handler', '_auto_collect_arguments', '_automatic_optimization', '_backward_hooks', '_buffers', '_call_batch_hook', '_call_impl',
'_current_fx_name', '_device', '_dtype', '_example_input_array', '_forward_hooks', '_forward_pre_hooks', '_get_backward_hooks', '_get_name', '_hparams', '_is_full_backward_hook', '_load_from_state_dict', 
'_load_state_dict_post_hooks', '_load_state_dict_pre_hooks', '_log_hyperparams', '_maybe_warn_non_full_backward_hook', '_metric_attributes', '_modules', '_named_members', '_non_persistent_buffers_set', 
'_on_before_batch_transfer', '_param_requires_grad_state', '_parameters', '_prevent_trainer_and_dataloaders_deepcopy', '_register_load_state_dict_pre_hook', 
'_register_sharded_tensor_state_dict_hooks_if_available', '_register_state_dict_hook', '_replicate_for_data_parallel', '_running_torchscript', '_running_torchscript_internal', '_save_to_state_dict', 
'_set_hparams', '_should_prevent_trainer_and_dataloaders_deepcopy', '_slow_forward', '_state_dict_hooks', '_to_hparams_dict', '_trainer', '_truncated_bptt_steps', '_use_amp', 
'_verify_is_manual_optimization', '_version', 'add_module', 'all_gather', 'allow_zero_length_dataloader_with_multiple_devices', 'apply', 'apply_counts', 'automatic_optimization', 'backward', 'bfloat16', 
'buffers', 'children', 'clip_gradients', 'compute_diffkeep_loss', 'compute_invar_loss', 'compute_loss', 'configure_callbacks', 'configure_gradient_clipping', 'configure_optimizers', 
'configure_sharded_model', 'cpu', 'cuda', 'current_epoch', 'decoder', 'decoder', 'device', 'diffkeep_angle_range', 'diffkeep_weight', 'double', 'dtype', 'dump_patches', 'encoder', 'encoder', 'eval', 
'example_input_array', 'extra_repr', 'float', 'forward', 'freeze', 'get_buffer', 'get_extra_state', 'get_parameter', 'get_submodule', 'global_rank', 'global_step', 'half', 'hparams', 'hparams_initial', 
'invar_angle_range', 'invar_mse_weight', 'ipu', 'load_from_checkpoint', 'load_state_dict', 'local_rank', 'log', 'log_dict', 'log_grad_norm', 'log_results', 'logger', 'loggers', 'lr', 'lr_scheduler_step', 
'lr_schedulers', 'manual_backward', 'min_nonz_frac', 'modules', 'named_buffers', 'named_children', 'named_modules', 'named_parameters', 'on_after_backward', 'on_after_batch_transfer', 'on_before_backward', 
'on_before_batch_transfer', 'on_before_optimizer_step', 'on_before_zero_grad', 'on_epoch_end', 'on_epoch_start', 'on_fit_end', 'on_fit_start', 'on_gpu', 'on_hpc_load', 'on_hpc_save', 'on_load_checkpoint', 
'on_predict_batch_end', 'on_predict_batch_start', 'on_predict_end', 'on_predict_epoch_end', 'on_predict_epoch_start', 'on_predict_model_eval', 'on_predict_start', 'on_pretrain_routine_end', 
'on_pretrain_routine_start', 'on_save_checkpoint', 'on_test_batch_end', 'on_test_batch_start', 'on_test_end', 'on_test_epoch_end', 'on_test_epoch_start', 'on_test_model_eval', 'on_test_model_train', 
'on_test_start', 'on_train_batch_end', 'on_train_batch_start', 'on_train_end', 'on_train_epoch_end', 'on_train_epoch_start', 'on_train_start', 'on_validation_batch_end', 'on_validation_batch_start', 
'on_validation_end', 'on_validation_epoch_end', 'on_validation_epoch_start', 'on_validation_model_eval', 'on_validation_model_train', 'on_validation_start', 'optimizer_step', 'optimizer_zero_grad', 
'optimizers', 'parameters', 'precision', 'predict_dataloader', 'predict_step', 'prepare_data', 'prepare_data_per_node', 'print', 'register_backward_hook', 'register_buffer', 'register_forward_hook', 
'register_forward_pre_hook', 'register_full_backward_hook', 'register_load_state_dict_post_hook', 'register_module', 'register_parameter', 'requires_grad_', 'save_hyperparameters', 'set_extra_state', 
'setup', 'share_memory', 'state_dict', 'tbptt_split_batch', 'teardown', 'test_dataloader', 'test_epoch_end', 'test_step', 'test_step_end', 'to', 'to_empty', 'to_onnx', 'to_torchscript', 'toggle_optimizer', 
'train', 'train_dataloader', 'trainer', 'training', 'training_epoch_end', 'training_step', 'training_step_end', 'transfer_batch_to_device', 'truncated_bptt_steps', 'type', 'unfreeze', 'untoggle_optimizer', 
'use_amp', 'val_dataloader', 'validation_epoch_end', 'validation_step', 'validation_step_end', 'worst_val_loss', 'worst_val_sample', 'worst_val_sample_idx', 'xpu', 'zero_grad']`

This is probably due to the __dir__ being overwritten somewhere as per https://stackoverflow.com/questions/59851684/python-duplicates-in-dir-is-it-a-bug

**Comment by supersergiy** [comment]
Is this us or `pytorch_lightning`?

**Comment by dodamih** [comment]
not sure
