### ISSUE TITLE
Chunk Blending

### ISSUE THREAD

**Issue by supersergiy** [ZettaAI/zetta_utils#140]
Ability to blend in XYZ across chunks.
Client flows must not know anything about how blending is implemented.

**Comment by supersergiy** [comment]
![image](https://user-images.githubusercontent.com/5151706/205726279-ead6a509-2178-42d0-bdd1-a4a0bc0ccdb8.png)

**Comment by supersergiy** [comment]
@dodamih how long do you think it will take you to have the `VolumetricBlendableApplyFlowSchema` write to 9 temporary outputs?

**Comment by supersergiy** [comment]
![image](https://user-images.githubusercontent.com/5151706/206008274-32ae669e-c3ac-4323-849f-ca1690a958e9.png)

**Comment by dodamih** [comment]
For cases where it doesn't fit into memory: What do you think about augmenting Layer with a subclass BlendableLayer or something like that so each worker can figure out the weighting from the chunking? The TaskableOperation still doesn't need to know anything since the info is carried by the subclass and the magic happens at BlendableLayer.write.

**Comment by supersergiy** [comment]
Hm, I would have to think more about the implications, but intuitively it doesn't feel like a natural way to distribute responsibilities. If this is something that only a `VolumetricBlendApplyFlowSchema` needs, we would hope the logic can be contained within its own code.

**Comment by supersergiy** [comment]
```python

blend pad < punk / 2

punk[i] % punk[i + 1]

blend = ??
blend_at_level = [Faslse, True, True]

blend_pads = [?, ?, ?]
blends/crops should be all the same or 0

if 8:
      (punk[i] + crop[i + 1]) % bunk[i]

      for i in [0, 1, 2]:
            boffset[i] = bcube[i].start = bcube[i - 1].start + crop_pad[i - 1]
            bunk[i] = largest N s.t. punk[i] % N == 0 under max_agg_chunk_size

            assert bunk[i] <= max_agg_chunk_size
            assert punk[i] % bunk[i] == 0
            assert bunk[i] * 2 <= punk[i]
            
           punk = 4096
           munk = 10k
           bunk = 2048
            
            # Hopefully doesn't matter:
            # crop = 128 ???
            # assert crop_pad[i] % bunk[i - 1] == 0
            # TODO:
            # assert blend_pad[i] < bunk[i]
```

**Comment by supersergiy** [comment]
![image](https://user-images.githubusercontent.com/5151706/211443515-15b1d8f3-156f-486c-9076-df505b394e41.png)

**Comment by supersergiy** [comment]
- [x] Subchunkable Flow is work with multiple levels
- [ ] No checkerboarding when unnecessary 
- [ ] Make `crop_pad` a requirement for blendable Operation
- [ ] `SubflowSchemaTask`(`SchemaBasedTask`?) with ParamSpecs
- [ ] Clean up the non-blend case
