### ISSUE TITLE
Make `subchunkable` usable by people who don't want to divide

### ISSUE THREAD

**Issue by supersergiy** [ZettaAI/zetta_utils#401]
There's 3 types of bbox expansion:
1. Resolution based expansion -- bbox given by the user does not evenly divide by the `dst_resolution`.
2. Bunk based expansion -- bbox given by the user doesn't align with bunk of the `dst` layer.
3. Punk based expansion -- .... with top level punk .... This is implemented as `expand_bbox` rn, and it moves bottom right corner.

Proposal:
Make each one of them a boolean parameter, apply those parameters independently in 1->2->3 order.

When both (2) and (3) are set, require some sort of divisibility between top level punk and dst.bunk.

**Comment by supersergiy** [comment]
@dodamih What do you think about the last possible mode:

Do (1) and (3), not (2), and allow non-alligned writes during the final write, either everywhere or at the boundaries only

**Comment by dodamih** [comment]
It's not difficult in principle, but we have enough case checking as is at the moment which will only increase with the PR that will fix this - I think allowing non-aligned writes at the top level should be a separate issue.
