### ISSUE TITLE
Investigate absolute vs relative path in infofile location vs cloudvolume directory for CVBackend

### ISSUE THREAD

**Issue by dodamih** [ZettaAI/zetta_utils#444]
Currently, ``CVBackend`` uses ``abspath`` for the cloudvolume directory but not the infofile location. Turning the infofile into absolutes broke some tests.

**Comment by dodamih** [comment]
@supersergiy I'm starting to look into this - I'm guessing our desired behaviour is that everything should work whether absolute or relative? Or do we want to require absolute in case it's running remotely?

**Comment by supersergiy** [comment]
I think it's OK to only allow absolute if it's less work, but the we have to throw on relative

**Comment by dodamih** [comment]
So even though I want to do something like "everything will be converted to absolute at the time of initialisation", this is bad because then running something remotely with intermediaries in say `~/zetta_temp/` on my local machine means that the backends will get initialised to `/home/dodam/zetta_temps` and then be serialised. As such, the backends will still have to support relatives.

I think I did figure out what was likely breaking, though, which was that `is_local` was happy to declare local paths without `file://` prefix to be remote.
