### ISSUE TITLE
Subchunkable constructor takes too long (~2 seconds)

### ISSUE THREAD

**Issue by supersergiy** [ZettaAI/zetta_utils#479]
@nkemnitz is running advanced scripts, each of which is scheduling _hundreds_ of subchunkable runs, and it takes many minutes to just construct all of the subchunkable flows. Link generation is already disabled.

Can we make subchunkable constructor faster?

**Comment by supersergiy** [comment]
@dodamih is this fixed? We narrowed the cause down to naive loki_logging, right? If that's the case, should we disable loki until #149 is addressed?

**Comment by dodamih** [comment]
Yeah - does anyone actually use loki at the moment?

**Comment by supersergiy** [comment]
@dodamih this is resolved, right?

**Comment by dodamih** [comment]
Yes - resolved by commenting out loki, so subsumed by #149.
