### ISSUE TITLE
Evaluate `posix_ipc` semaphore solution

### ISSUE THREAD

**Issue by supersergiy** [ZettaAI/zetta_utils#499]
Make a mock up system with two stages (A and B). We have a 20 tasks (2 stages each). B stage depends on completion of the A stage. A stage takes 1 second. B stage takes half a second. Semaphore width for both stages if 4. Verify how fast we can get with the `posix_ipc` semaphore on the worker hardware setup. 

Also, verify that semaphore does work across multiple independent python invocations.

**Comment by nkemnitz** [comment]
Not sure if this is helpful - we had a mutex solution in SEAMLeSS at some point: https://github.com/seung-lab/SEAMLeSS/blob/master/inference/worker.py#L95
