### ISSUE TITLE
Multinode Multi-GPU DDP only uses single GPU per node

### ISSUE THREAD

**Issue by nkemnitz** [ZettaAI/zetta_utils#541]
Only saw 1 GPU on each of my two nodes getting utilized.

**Comment by supersergiy** [comment]
How does the speed of 4x1 node DDP compare to 1x4 DDP? It would be useful to gauge the priority of this issue. Maybe just spinning up a large number of single GPU workers is sufficient for most usecases

**Comment by supersergiy** [comment]
Also, could you share the specs that you used to train?

**Comment by akhileshh** [comment]
[nproc_per_node](https://github.com/ZettaAI/zetta_utils/blob/34e73e677d21c27a911c89ead7295ec1c54e6221/zetta_utils/training/lightning/train.py#L106) needs to be set for this; and maybe the `devices` arg to `Trainer` too, if the default `auto` doesn't work.

**Comment by supersergiy** [comment]
@nkemnitz did setting the parameters help or is this issue actually a bug?

**Comment by nkemnitz** [comment]
I have not tried, but pretty sure this would solve the issue. Can't we automatically get/set that from either the GPUs requested in `lightning_train_remote.worker_resources` or the `lightning_train.trainer.devices`?

**Comment by akhileshh** [comment]
It can now be set explicitly (#553 ). We could make the default `-1`, and set to all available GPUs when `nproc_per_node=-1`.

**Comment by supersergiy** [comment]
Using all available GPUs as the default makes sense to me
