### ISSUE TITLE
Remote workers cannot write to local intermediaries

### ISSUE THREAD

**Issue by trivoldus28** [ZettaAI/zetta_utils#644]
When running a job with remote workers and utilizing intermediaries, errors similar to this would happen:
```
FileNotFoundError: The infofile at                                                 
'file:///opt/zetta_utils/zetta_utils/tmp0/chunks_level_1/subchunkable-f36075907972f
3208acf6e32ddeb21da_DelegatedSubchunkedOperation_temp_(29696.0, 16384.0, 2000.0) - 
(30720.0, 17408.0, 2010.0)_None/info' does not exist.
```

This bug is new and fairly important because if the user wants to use multiple levels of subchunkable, or not able to skip intermediaries and write directly to `dst`, zutils can't run it.

Example log: https://gist.github.com/trivoldus28/bb50274823cab22041b989005ce1631b

Timeline of bug existence (should really perform a precise bisect):
- 10/18/23 (bac1ddb331527aea2144cec616385b27ab33dd16): bug not present
- 11/07/23 (522b3775ce8f42da24b7a7a10207489d2cf45fc0): bug present
- 02/16/24 (9295d11ce0d53c48fe1ce4b49b5901ce4f8b5838): bug still present

Example CUE for testing: https://gist.github.com/trivoldus28/f2e5a8e799296f108dc54c7f5e03eae9
- Adapted from an example in the [tutorial](https://zetta.ai/zetta_utils/subchunkable_apply_flow_quick_start_guide.html#running-remotely)

Tested worker images:
- `us-east1-docker.pkg.dev/zetta-research/zutils/zetta_utils:tri-231018`: works
- `us-east1-docker.pkg.dev/zetta-research/zutils/zetta_utils:tri-231107a`: doesn't works
- `us-east1-docker.pkg.dev/zetta-research/zutils/zetta_utils:tri-240216`: doesn't works

**Comment by dodamih** [comment]
Closed by #660.
