### ISSUE TITLE
Implement `enforce_chunk_aligned_writes` for TensorStore backend

### ISSUE THREAD

**Issue by trivoldus28** [ZettaAI/zetta_utils#645]
Currently zutils can't run jobs with chunk aligned writes to TS backend because `enforce_chunk_aligned_writes` is [asserted](https://github.com/ZettaAI/zetta_utils/blob/main/zetta_utils/layer/volumetric/tensorstore/backend.py#L266)/not implemented. We should implement this check in the `write` fn and remove the assertion.

**Comment by trivoldus28** [comment]
@dodamih let me know if it's something easy for you to do or if you'd want me to give a try.

**Comment by dodamih** [comment]
I can do it.
