### ISSUE TITLE
Subchunkable: blend mode "defer"

### ISSUE THREAD

**Issue by JoeStrout** [ZettaAI/zetta_utils#646]
## Motivation

Sometimes we have work that can't be simply blended across chunk boundaries (for example, segmentation).  In this case, the user wants to specify blend_pads as usual, but defer the usual blending, and have as their output the intermediate checkerboard layers.  They can then run those 4 or 8 layers through whatever bespoke or more-complex code they need to produce one unified, coherent output.

## API Changes

In `build_subchunkable_apply_flow`, the `processing_blend_modes` parameter currently accepts "linear" or "quadratic".  We will add a third mode, "defer".  When this mode is selected:

1. Destination layer (`dst`) must _not_ be `None`
2. `skip_intermediaries` must be `False`
3. Files will be left in `level_intermediaries_dirs[-1]`
4. Those files will use a more human-readable naming scheme (skipping the usual hashes used to avoid conflicts when multiple jobs are sharing the same intermediary directory).  These names will favor underscores and avoid slashes, spaces, and parentheses, to make them easier to use on the command line.

As a related task that came up during implementation:

5. The three _procs properties (write_procs etc.), currently defined in `VolumetricLayer`, should be added to `VolumetricBasedLayerProtocol`.  This simplifies type-checking and mypy-wrestling, as it means we can count on anything implementing that protocol having these properties.

**Comment by dodamih** [comment]
Oh, I also just noticed - `level_intermediaries_dirs` is largest first, so it'd actually be `level_intermediaries_dirs[0]`.
