### ISSUE TITLE
Saving models using JIT

### ISSUE THREAD

**Issue by dodamih** [ZettaAI/zetta_utils#99]
Saving models using JIT is better since it (a) does not require that zetta_utils be installed on worker nodes, and (b) whether the worker can run the command is not dependent on the version of zetta_utils (in case there is an architecture change for the network that changes variable names or behaviour). The downside is that the saved serialised files are harder to human-read, which is mitigated by having the JSON output of the architecture.

We should add JIT saving in lightning by default, if we can figure out a good way to get the correct input for torch.jit.trace.

**Comment by supersergiy** [comment]
@dodamih This is becoming urgent -- @nkemnitz is spending time in ad-hoc ways to convert his models to `corgie`. 
Can you look at this and make a pull request ASAP? The place to start looking is https://github.com/ZettaAI/zetta_utils/blob/main/zetta_utils/training/lightning/trainers/default.py#L19

**Comment by supersergiy** [comment]
resolved via #130
